- name: install mysql 
  hosts: mysql
  become: yes
  tasks: 

    - name: disable MySQL 8 version
      ansible.builtin.command: dnf module disable mysql -y

    - name: setup mysql 5.7 repo
      ansible.builtin.copy: 
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo


    - name: install MYSQL 
      ansible.builtin.dnf:
        name: mysql-community-server 
        state: present

    - name: Start and enable mysql
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: setup root password
      ansible.builtin.shell or command: mysql_secure_installation --set-root-pass RoboShop@1

