- name: redis
  hosts: redis
  become: yes
  tasks:
  
  - name: install rep rpm
    ansible.builtin.dnf: 
      name: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
      state: present
      disable_gpg_check: true

  - name : enable redis6.2
    ansible.builtin.command: dnf module enable redis:remi-6.2 -y
    
  - name: Install redis
    ansible.builtin.package:
        name: redis
        state: present
  - name: allow remote connectios
    ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

  - name: enable and start redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes

        
  